### ISSUE TITLE
Make scripts generalizable

### ISSUE THREAD

**Issue by alexkeating** [ScopeLift/l2-flexible-voting#16]
Currently the deploy and testing scripts are only meant to be used with avalance fuji and polygon mumbai. Instead, they should support any chain as an L1 and an L2 as long as those chains are supported by Wormhole.

Some strategies we discussed were:
1. Interpolating a chain id into the broadcast file path
2. using some config 

_Originally posted by @apbendi in https://github.com/ScopeLift/l2-flexible-voting/pull/15#discussion_r1253588160_

**Comment by apbendi** [comment]
Note: we can pull token names/symbol data directly from the L1 before deploying on the L2.

**Comment by alexkeating** [comment]
Adding a link to thread about L1 data for more context https://github.com/ScopeLift/l2-flexible-voting/pull/15#discussion_r1248229523
