### ISSUE TITLE
Update voting interfaces to align with the Governor

### ISSUE THREAD

**Issue by alexkeating** [ScopeLift/l2-flexible-voting#19]
The L2 Voting Aggregator can and should be made to align with the contract methods from the Governor itself. This will allow the aggregator contract to be added to tools like Tally such that users can cast and view votes there. We should also make sure the ERC20Votes contract we are using will work out of the box with Tally.

_Also see original post by @alexkeating in https://github.com/ScopeLift/l2-flexible-voting/pull/9#discussion_r1264738134_

**Comment by alexkeating** [comment]
@apbendi Should we add the other cast methods to the L2VoteAggregator contract?

**Comment by wildmolasses** [comment]
https://hackmd.io/AaXo30_dRMiqhNgrAKLqOg
