### ISSUE TITLE
L1 Contract Gas Optimizations

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/l2-flexible-voting#30]
Look for opportunities to reduce gas costs in the Layer 1 contracts, such as:

* Reducing storage writes
* Packing storage slots
* Unchecked math where possible
* Using custom errors
* [Etc](https://0xmacro.com/blog/solidity-gas-optimizations-cheat-sheet/)...

**Comment by alexkeating** [comment]
- If we use create we can make some addresses constant.
