### ISSUE TITLE
Make contracts more robust to errors and edge cases

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/l2-flexible-voting#32]
Things to consider:

* Delays or failures in message passing
* What happens if a cross chain message reverts?
* What happens if there is an invalid proposal state, message passed after voting has ended, etc...
* Edge cases related to usage of the L1 block for checkpointing

**Comment by alexkeating** [comment]
Adding checkboxes here for edgecases:

- [ ] Handle delayed message
- [ ] Handle failed message
- [ ] Handle cross chain revert
- [ ] Handle message after voting has ended
- [ ] Handle message before message has begun
- [ ] Handle edge cases with L1 block number or L1 timestamp

**Comment by alexkeating** [comment]
If a message is delayed it could be resent. A couple things could be happening with the delay:

1. Validators could be trying to censor the messsage
2. The relaying infrastructure is down

In the first case there isn't much we can do accept to keeping sending messages and hope one gets through. In the second case a dao could have a fallback specialized relayer they are running. We could make a generic specialized relayer for DAOs to deploy. It would also require us to modify the contracts for a specialized relayer call.

**Comment by alexkeating** [comment]
Here is the contract and method a dao specific relayer could call to deliver a message.

https://github.com/wormhole-foundation/wormhole/blob/main/ethereum/contracts/relayer/wormholeRelayer/WormholeRelayerDelivery.sol#L55

**Comment by alexkeating** [comment]
I think this is the logic for the generic relayer where it makes the cross chain call with the VAA.

https://github.com/wormhole-foundation/wormhole/blob/bd666ef076c4ac97325c687143b54eb7e5f4ff47/relayer/generic_relayer/relayer-engine-v2/src/processor.ts#L220

**Comment by alexkeating** [comment]
So delayed message by relayer should be manually submitted through the frontend

**Comment by alexkeating** [comment]
This has been handled
